name: Java CI

on:
    push:
        branches:
            - java
    pull_request:
        branches:
            - java

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: get-repo-name
      run: |
        target=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
        echo "::set-output name=RESULT::$target"
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build mod jar
      run: |
        chmod +x gradlew
        ./gradlew jar
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.get-repo-name.outputs.RESULT }}
        path: build/libs/${{  steps.get-repo-name.outputs.RESULT }}-java.jar
